"""Corpus construction: scan cloned repositories into per-language file lists.

Files are filtered (size bounds, UTF-8 validity, excluded directories,
generated/vendored/minified heuristics) and content-deduplicated, producing a
deterministic list of `FileRecord`s per language from which measurement
windows are assembled.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

from .languages import (
    EXCLUDED_DIRS,
    LANGUAGES,
    MAX_FILE_BYTES,
    MIN_FILE_BYTES,
    LanguageConfig,
)


@dataclass(frozen=True)
class FileRecord:
    language: str
    repo: str           # repo directory name, e.g. "mathlib4"
    rel_path: str       # path within the repo
    abs_path: str
    n_bytes: int

    @property
    def display_path(self) -> str:
        return f"{self.repo}/{self.rel_path}"


def _is_excluded(rel_parts: tuple[str, ...]) -> bool:
    return any(part.lower() in EXCLUDED_DIRS for part in rel_parts[:-1])


def _looks_generated(text: str, cfg: LanguageConfig) -> bool:
    """Heuristics for machine-generated or minified files."""
    head = text[:2048].lower()
    for marker in ("do not edit", "auto-generated", "autogenerated", "automatically generated", "@generated"):
        if marker in head:
            return True
    # Minified/one-line files: absurdly long average line length.
    lines = text.splitlines()
    if lines and len(text) / max(len(lines), 1) > 500:
        return True
    return False


def scan_language(corpora_dir: str | Path, language: str) -> list[FileRecord]:
    """Scan `corpora_dir/<language>/<repo>/**` into a sorted list of files."""
    cfg = LANGUAGES[language]
    root = Path(corpora_dir) / language
    records: list[FileRecord] = []
    seen_hashes: set[bytes] = set()
    if not root.is_dir():
        raise FileNotFoundError(f"no corpus directory {root}")
    for repo_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        for path in sorted(repo_dir.rglob("*")):
            if not path.is_file():
                continue
            if path.suffix.lower() not in cfg.extensions:
                continue
            rel = path.relative_to(repo_dir)
            if _is_excluded(rel.parts):
                continue
            name = path.name.lower()
            if any(s in name for s in cfg.exclude_file_substrings):
                continue
            try:
                data = path.read_bytes()
            except OSError:
                continue
            if not (MIN_FILE_BYTES <= len(data) <= MAX_FILE_BYTES):
                continue
            try:
                text = data.decode("utf-8")
            except UnicodeDecodeError:
                continue
            if _looks_generated(text, cfg):
                continue
            digest = hashlib.sha256(data).digest()
            if digest in seen_hashes:  # dedup identical vendored copies
                continue
            seen_hashes.add(digest)
            records.append(
                FileRecord(
                    language=language,
                    repo=repo_dir.name,
                    rel_path=str(rel),
                    abs_path=str(path),
                    n_bytes=len(data),
                )
            )
    return records


def corpus_stats(records: list[FileRecord]) -> dict:
    total = sum(r.n_bytes for r in records)
    return {
        "n_files": len(records),
        "total_bytes": total,
        "mean_file_bytes": total / len(records) if records else 0.0,
        "repos": sorted({r.repo for r in records}),
    }
